summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/fpliu1214/uppm-package-repository-android-31-aarch64/releases/download/2024.09.12/fontconfig-2.15.0-android-31-arm64-v8a.tar.xz
bin-sha: 7e6874c1ddcae51f7336e6d9301270b1b0a0ada7a056424da99a13f874fddcc5
