summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/fpliu1214/uppm-package-repository-android-31-aarch64/releases/download/2024.09.12/pkg-config-0.29.2-android-31-arm64-v8a.tar.xz
bin-sha: 6311b783c209015ee768f7e245f32c07b3bcdb2cd78beefa485a5be76afb4ff8
